#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-.}"
cd "$ROOT"

if [ ! -f "monad.toml" ]; then
  echo "ERROR: monad.toml not found. Run from repo root." >&2
  exit 1
fi

if [ ! -f "crates/monad-cli/src/lib.rs" ]; then
  echo "ERROR: crates/monad-cli/src/lib.rs not found." >&2
  exit 1
fi

cp crates/monad-cli/src/lib.rs crates/monad-cli/src/lib.rs.bak.layer-0002-hotfix-0015

python3 - <<'PY'
from pathlib import Path
import re

path = Path("crates/monad-cli/src/lib.rs")
text = path.read_text()

def replace_function(source: str, function_name: str, replacement: str) -> str:
    needle = f"fn {function_name}"
    start = source.find(needle)
    if start == -1:
        raise SystemExit(f"ERROR: could not find function `{function_name}`")

    brace = source.find("{", start)
    if brace == -1:
        raise SystemExit(f"ERROR: could not find opening brace for `{function_name}`")

    depth = 0
    for index in range(brace, len(source)):
        char = source[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                end = index + 1
                return source[:start] + replacement + source[end:]

    raise SystemExit(f"ERROR: could not find end of `{function_name}`")

# Dispatch apply before the generic placeholder arm.
if 'Some(("apply", sub)) => emit_apply(sub, json),' not in text:
    marker = 'Some(("plan", sub)) => emit_plan(sub, json),'
    if marker not in text:
        raise SystemExit("ERROR: could not find `plan` dispatch arm. Run layer-0002-hotfix-0014 first.")
    text = text.replace(marker, marker + '\n        Some(("apply", sub)) => emit_apply(sub, json),', 1)

apply_cmd = r'''fn apply_cmd() -> Command {
    Command::new("apply")
        .about("Safely inspect and eventually apply a previously generated Monad change plan")
        .arg(arg("plan-file", "Path to a plan file generated by `monad plan --out`").required(true))
        .arg(flag("dry-run", "Validate and summarize the plan without applying it"))
        .arg(flag("yes", "Skip safe confirmations when apply execution is implemented"))
        .arg(fmt_arg().value_parser(["text", "json", "markdown"]))
}'''

text = replace_function(text, "apply_cmd", apply_cmd)

insert_before = '\n#[derive(Debug, Serialize)]\nstruct PlaceholderOutput'
if insert_before not in text:
    raise SystemExit("ERROR: could not find PlaceholderOutput insertion point")

apply_code = r'''
#[derive(Debug, Serialize)]
struct ApplyCommandOutput {
    schema_version: u32,
    command: &'static str,
    status: &'static str,
    implemented: bool,
    plan_file: String,
    plan_file_bytes: u64,
    inferred_plan_format: String,
    dry_run: bool,
    mutating: bool,
    plan_backed: bool,
    did_mutate: bool,
    message: String,
    next: String,
    preview: String,
}

fn emit_apply(matches: &ArgMatches, json: bool) -> Result<(), String> {
    let plan_file = matches
        .get_one::<String>("plan-file")
        .ok_or_else(|| "missing required plan-file".to_string())?
        .to_string();

    let format = matches
        .get_one::<String>("format")
        .map(String::as_str)
        .unwrap_or("text");

    let dry_run = matches.get_flag("dry-run");

    let contents = std::fs::read_to_string(&plan_file)
        .map_err(|error| format!("failed to read plan file `{plan_file}`: {error}"))?;

    if contents.trim().is_empty() {
        return Err(format!("plan file `{plan_file}` is empty"));
    }

    let output = build_apply_output(plan_file, contents, dry_run);
    let rendered = render_apply_output(&output, if json { "json" } else { format })?;

    println!("{rendered}");

    Ok(())
}

fn build_apply_output(plan_file: String, contents: String, dry_run: bool) -> ApplyCommandOutput {
    let trimmed = contents.trim_start();

    let inferred_plan_format = if trimmed.starts_with('{') {
        "json"
    } else if trimmed.starts_with("# ") || trimmed.starts_with("## ") {
        "markdown"
    } else {
        "text"
    }
    .to_string();

    let preview = contents
        .lines()
        .take(12)
        .collect::<Vec<_>>()
        .join("\n")
        .chars()
        .take(800)
        .collect::<String>();

    ApplyCommandOutput {
        schema_version: monad_core::PLAN_SCHEMA_VERSION,
        command: "apply",
        status: "not_implemented",
        implemented: false,
        plan_file,
        plan_file_bytes: contents.len() as u64,
        inferred_plan_format,
        dry_run,
        mutating: monad_core::command_catalog::is_mutating_command("apply"),
        plan_backed: monad_core::command_catalog::is_plan_backed("apply"),
        did_mutate: false,
        message: "`monad apply` can read and validate a plan file in WP-0001, but execution is intentionally disabled. No repository changes were made.".to_string(),
        next: "Future work packets will add signed plan validation, plan schema parsing, lockfile checks, approval gates, and actual apply execution.".to_string(),
        preview,
    }
}

fn render_apply_output(output: &ApplyCommandOutput, format: &str) -> Result<String, String> {
    match format {
        "json" => serde_json::to_string_pretty(output).map_err(|error| error.to_string()),
        "markdown" => Ok(render_apply_markdown(output)),
        "text" => Ok(render_apply_text(output)),
        other => Err(format!("unsupported apply output format `{other}`")),
    }
}

fn render_apply_text(output: &ApplyCommandOutput) -> String {
    let mut rendered = String::new();

    rendered.push_str("Monad Apply Preview\n");
    rendered.push_str("===================\n\n");
    rendered.push_str(&format!("status: {}\n", output.status));
    rendered.push_str(&format!("implemented: {}\n", output.implemented));
    rendered.push_str(&format!("plan file: {}\n", output.plan_file));
    rendered.push_str(&format!("plan file bytes: {}\n", output.plan_file_bytes));
    rendered.push_str(&format!(
        "inferred plan format: {}\n",
        output.inferred_plan_format
    ));
    rendered.push_str(&format!("dry-run: {}\n", output.dry_run));
    rendered.push_str(&format!("mutating command: {}\n", output.mutating));
    rendered.push_str(&format!("plan-backed: {}\n", output.plan_backed));
    rendered.push_str(&format!("did mutate: {}\n", output.did_mutate));
    rendered.push_str("\n");
    rendered.push_str(&output.message);
    rendered.push_str("\n");
    rendered.push_str(&output.next);
    rendered.push_str("\n\npreview:\n");
    rendered.push_str(&output.preview);
    rendered.push('\n');

    rendered
}

fn render_apply_markdown(output: &ApplyCommandOutput) -> String {
    let mut rendered = String::new();

    rendered.push_str("# Monad Apply Preview\n\n");
    rendered.push_str(&format!("- **Status:** `{}`\n", output.status));
    rendered.push_str(&format!("- **Implemented:** `{}`\n", output.implemented));
    rendered.push_str(&format!("- **Plan file:** `{}`\n", output.plan_file));
    rendered.push_str(&format!(
        "- **Plan file bytes:** `{}`\n",
        output.plan_file_bytes
    ));
    rendered.push_str(&format!(
        "- **Inferred plan format:** `{}`\n",
        output.inferred_plan_format
    ));
    rendered.push_str(&format!("- **Dry-run:** `{}`\n", output.dry_run));
    rendered.push_str(&format!("- **Mutating command:** `{}`\n", output.mutating));
    rendered.push_str(&format!("- **Plan-backed:** `{}`\n", output.plan_backed));
    rendered.push_str(&format!("- **Did mutate:** `{}`\n\n", output.did_mutate));
    rendered.push_str("## Message\n\n");
    rendered.push_str(&output.message);
    rendered.push_str("\n\n");
    rendered.push_str("## Next\n\n");
    rendered.push_str(&output.next);
    rendered.push_str("\n\n");
    rendered.push_str("## Preview\n\n```text\n");
    rendered.push_str(&output.preview);
    rendered.push_str("\n```\n");

    rendered
}

'''

text = text.replace(insert_before, "\n" + apply_code + insert_before, 1)
path.write_text(text)
PY

mkdir -p crates/monad-cli/tests

cat > crates/monad-cli/tests/apply_command.rs <<'RS'
use std::fs;
use std::process::Command;

fn temp_plan_path(name: &str, extension: &str) -> std::path::PathBuf {
    let mut path = std::env::temp_dir();
    path.push(format!(
        "monad-apply-test-{}-{name}.{extension}",
        std::process::id()
    ));
    path
}

#[test]
fn apply_reads_existing_plan_without_mutating() {
    let plan = temp_plan_path("plan", "md");

    fs::write(
        &plan,
        "# Monad Change Plan\n\n- **Operation:** `add`\n\n## Steps\n\n1. validate\n",
    )
    .expect("should write temp plan");

    let output = Command::new(env!("CARGO_BIN_EXE_monad"))
        .args([
            "apply",
            plan.to_str().expect("temp path should be utf-8"),
            "--dry-run",
        ])
        .output()
        .expect("monad apply should run");

    let _ = fs::remove_file(&plan);

    assert!(output.status.success());

    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(stdout.contains("Monad Apply Preview"));
    assert!(stdout.contains("status: not_implemented"));
    assert!(stdout.contains("implemented: false"));
    assert!(stdout.contains("dry-run: true"));
    assert!(stdout.contains("did mutate: false"));
    assert!(stdout.contains("execution is intentionally disabled"));
}

#[test]
fn apply_can_render_json() {
    let plan = temp_plan_path("plan", "json");

    fs::write(
        &plan,
        r#"{
  "command": "plan",
  "operation": "add",
  "status": "implemented"
}
"#,
    )
    .expect("should write temp plan");

    let output = Command::new(env!("CARGO_BIN_EXE_monad"))
        .args([
            "apply",
            plan.to_str().expect("temp path should be utf-8"),
            "--dry-run",
            "--format",
            "json",
        ])
        .output()
        .expect("monad apply --format json should run");

    let _ = fs::remove_file(&plan);

    assert!(output.status.success());

    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(stdout.contains(r#""command": "apply""#));
    assert!(stdout.contains(r#""status": "not_implemented""#));
    assert!(stdout.contains(r#""implemented": false"#));
    assert!(stdout.contains(r#""did_mutate": false"#));
    assert!(stdout.contains(r#""inferred_plan_format": "json""#));
}

#[test]
fn apply_fails_for_missing_plan_file() {
    let plan = temp_plan_path("missing", "json");

    let output = Command::new(env!("CARGO_BIN_EXE_monad"))
        .args(["apply", plan.to_str().expect("temp path should be utf-8")])
        .output()
        .expect("monad apply missing file should run and fail cleanly");

    assert!(!output.status.success());

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("failed to read plan file"));
}
RS

cargo fmt --all

echo
echo "Applied layer-0002-hotfix-0015-safe-monad-apply-plan-reader"
echo
echo "Implemented:"
echo "  - safe monad apply plan-file reader"
echo "  - text/json/markdown apply preview output"
echo "  - explicit non-mutating WP-0001 apply behavior"
echo "  - apply command integration tests"
